##############################################################################
# Genomes and annotation files 
##############################################################################

# GTF file for genome build ensembl 90 
gtf_file:
  /home/groups/CEDAR/callahro/cfrna_references/ensembl_109/gencode.v43.chr_patch_hapl_scaff.annotation.gtf
TE_gtf:
  /home/groups/CEDAR/callahro/cfrna_references/hg38_rmsk_TE.gtf

#prebuilt star index
star_index:
  /home/groups/CEDAR/callahro/cfrna_references/ensembl_109/STAR_index

#genome location
genome:
  /home/groups/CEDAR/callahro/cfrna_references/ensembl_109/GRCh38.p13.genome.fa

#fasta for circExplorer
ref_fa_exp:
  /home/groups/CEDAR/spilioto/tools/hg38.fa
  
#gtf for circExplorer
ref_txt_exp:
  /home/groups/CEDAR/spilioto/tools/hg38_ref_2023.txt

#star index for circExplorer
star_index_exp:
  /home/groups/CEDAR/spilioto/tools/hg38_ref_star_index

####################################################################
# TOOLS 
####################################################################
#star tool location
star_tool:
  /home/groups/CEDAR/tools/STAR/tags/2.5.3a/bin/Linux_x86_64/STAR

#picart tool location
picard_tool:
  /home/groups/CEDAR/tools/picard-tools-1.119/MarkDuplicates.jar

sickle_tool:
  /home/groups/CEDAR/tools/sickle

#############################################################################################
# Overall roject information 
#############################################################################################
project_name:
  "test_project"
metadata:
  "./test_project_metadata.txt"
glob_path:
  "samples/raw/{sample}_R1.fq"
gscratch_path:
  "/home/exacloud/gscratch/CEDAR/cfRNA-seq-pipeline/multi_omic_pipeline/"


